    "langchain>=0.1.0",
    "langchain-community>=0.0.20",
    "sentence-transformers>=2.2.0",
    "faiss-cpu>=1.7.4",
    "pypdf>=3.17.0",
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.27.0",
    "python-multipart>=0.0.6",